spring:
  h2:
    console:
      enabled: true
      path: /wicoin
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:wicoin;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    username: root
    password: root
    driver-class-name: org.h2.driver
server:
  port: 7070