CREATE TABLE IF NOT EXISTS wiuser (
    ID           INTEGER         NOT NULL AUTO_INCREMENT,
    USERNAME     VARCHAR(255)    NOT NULL,
    EMAIL        VARCHAR(255)    NOT NULL,
    PASSWORD     VARCHAR(255)    NOT NULL,
    PRIMARY KEY (ID)
);