CREATE TABLE IF NOT EXISTS wiuser (
    ID           INTEGER         NOT NULL AUTO_INCREMENT,
    USERNAME     VARCHAR(255)    NOT NULL,
    EMAIL        VARCHAR(255)    NOT NULL,
    PASSWORD     VARCHAR(255)    NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS wallet (
    WALLET_ID    VARCHAR(255)   NOT NULL,
    PUBLIC_KEY   CLOB           NOT NULL,
    PRIVATE_KEY  CLOB           NOT NULL,
    WIUSER_ID    INTEGER        NOT NULL,
    PRIMARY KEY (WALLET_ID),
    FOREIGN KEY (WIUSER_ID) REFERENCES wiuser (ID)
);
